## Rutas de la API crud

## Auth
### Registro de usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@gmail.com",
  "password": "123456",
  "role": "user"
}

### LOGIN DE USUARIO
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "login": "user2@gmail.com",
  "password": "123456"
}

### 🔐 OBTENER PERFIL (Necesita Token)
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjdkOGE1ZmFlN2MwYTdhY2VhNWU1MTQ4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyMjUyMTE4LCJleHAiOjE3NDIyNTU3MTh9.2TJyfV1W8kK6Bu_GHz8pu3tNdJ1Q9BiIA8_du8ALWkk

###

### 🛒 CREAR PRODUCTO (Necesita Token)
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYSIsInN1YiI6IjY3ZDhiYzFhOTU2ZjVhMTU4NjI2MmExZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQyMjYzNzQ1LCJleHAiOjE3NDIyNjczNDV9.0-_Q0SZn4aS6cMyRDP-NduWHTuEmKWLiH4o4f7h9_tM
Content-Type: application/json

{
  "nombre": "Laptop",
  "descripcion": "Potente equipo",
  "precio": 1500,
  "categoria": "Electrónica"
}

###

### LISTAR TODOS LOS PRODUCTOS
GET http://localhost:3000/products

###

### OBTENER UN PRODUCTO POR ID
GET http://localhost:3000/products/67d8a86ecb7d8346f6b74f72

###

###  ACTUALIZAR PRODUCTO (PATCH, Necesita Token)
PATCH http://localhost:3000/products/67d8a86ecb7d8346f6b74f72
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYSIsInN1YiI6IjY3ZDhiYzFhOTU2ZjVhMTU4NjI2MmExZSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQyMjYzNzQ1LCJleHAiOjE3NDIyNjczNDV9.0-_Q0SZn4aS6cMyRDP-NduWHTuEmKWLiH4o4f7h9_tM
Content-Type: application/json

{
  "precio": 1600
}

###

### 🗑 ELIMINAR PRODUCTO (Necesita Token)
DELETE http://localhost:3000/products/67d8a86ecb7d8346f6b74f72
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjdkOGE1ZmFlN2MwYTdhY2VhNWU1MTQ4Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyMjUyMTE4LCJleHAiOjE3NDIyNTU3MTh9.2TJyfV1W8kK6Bu_GHz8pu3tNdJ1Q9BiIA8_du8ALWkk
